version: '3.8'
services:
  cache:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: cache-redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - default
    ports:
      - '7785:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - cache:/usr/local/etc/redis/redis.conf
      - cache:/var/lib/redis
volumes:
  cache:
    driver: local